[package]
name = "ethdownloader"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0.14"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4.11", features = ["derive"] }
